/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NicoRouteImport } from './routes/nico'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPrivacyRouteImport } from './routes/_authenticated/privacy'
import { Route as MobileIndexRouteImport } from './routes/mobile/index'
import { Route as MobileSettingsRouteImport } from './routes/mobile/settings'
import { Route as ApiNicoSpeakRouteImport } from './routes/api/nico/speak'
import { Route as ApiNicoThinkRouteImport } from './routes/api/nico/think'
import { Route as ApiNicoTranscribeRouteImport } from './routes/api/nico/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NicoRoute = NicoRouteImport.update({
  id: '/nico',
  path: '/nico',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrivacyRoute = AuthenticatedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MobileIndexRoute = MobileIndexRouteImport.update({
  id: '/mobile/',
  path: '/mobile/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileSettingsRoute = MobileSettingsRouteImport.update({
  id: '/mobile/settings',
  path: '/mobile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNicoSpeakRoute = ApiNicoSpeakRouteImport.update({
  id: '/api/nico/speak',
  path: '/api/nico/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNicoThinkRoute = ApiNicoThinkRouteImport.update({
  id: '/api/nico/think',
  path: '/api/nico/think',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNicoTranscribeRoute = ApiNicoTranscribeRouteImport.update({
  id: '/api/nico/transcribe',
  path: '/api/nico/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nico': typeof NicoRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/mobile/settings': typeof MobileSettingsRoute
  '/mobile/': typeof MobileIndexRoute
  '/api/nico/speak': typeof ApiNicoSpeakRoute
  '/api/nico/think': typeof ApiNicoThinkRoute
  '/api/nico/transcribe': typeof ApiNicoTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nico': typeof NicoRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/mobile/settings': typeof MobileSettingsRoute
  '/mobile': typeof MobileIndexRoute
  '/api/nico/speak': typeof ApiNicoSpeakRoute
  '/api/nico/think': typeof ApiNicoThinkRoute
  '/api/nico/transcribe': typeof ApiNicoTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/nico': typeof NicoRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/privacy': typeof AuthenticatedPrivacyRoute
  '/mobile/settings': typeof MobileSettingsRoute
  '/mobile/': typeof MobileIndexRoute
  '/api/nico/speak': typeof ApiNicoSpeakRoute
  '/api/nico/think': typeof ApiNicoThinkRoute
  '/api/nico/transcribe': typeof ApiNicoTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/nico'
    | '/settings'
    | '/sitemap.xml'
    | '/dashboard'
    | '/privacy'
    | '/mobile/settings'
    | '/mobile/'
    | '/api/nico/speak'
    | '/api/nico/think'
    | '/api/nico/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/nico'
    | '/settings'
    | '/sitemap.xml'
    | '/dashboard'
    | '/privacy'
    | '/mobile/settings'
    | '/mobile'
    | '/api/nico/speak'
    | '/api/nico/think'
    | '/api/nico/transcribe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/nico'
    | '/settings'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/privacy'
    | '/mobile/settings'
    | '/mobile/'
    | '/api/nico/speak'
    | '/api/nico/think'
    | '/api/nico/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NicoRoute: typeof NicoRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MobileSettingsRoute: typeof MobileSettingsRoute
  MobileIndexRoute: typeof MobileIndexRoute
  ApiNicoSpeakRoute: typeof ApiNicoSpeakRoute
  ApiNicoThinkRoute: typeof ApiNicoThinkRoute
  ApiNicoTranscribeRoute: typeof ApiNicoTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nico': {
      id: '/nico'
      path: '/nico'
      fullPath: '/nico'
      preLoaderRoute: typeof NicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privacy': {
      id: '/_authenticated/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/mobile/': {
      id: '/mobile/'
      path: '/mobile'
      fullPath: '/mobile/'
      preLoaderRoute: typeof MobileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/settings': {
      id: '/mobile/settings'
      path: '/mobile/settings'
      fullPath: '/mobile/settings'
      preLoaderRoute: typeof MobileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nico/speak': {
      id: '/api/nico/speak'
      path: '/api/nico/speak'
      fullPath: '/api/nico/speak'
      preLoaderRoute: typeof ApiNicoSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nico/think': {
      id: '/api/nico/think'
      path: '/api/nico/think'
      fullPath: '/api/nico/think'
      preLoaderRoute: typeof ApiNicoThinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nico/transcribe': {
      id: '/api/nico/transcribe'
      path: '/api/nico/transcribe'
      fullPath: '/api/nico/transcribe'
      preLoaderRoute: typeof ApiNicoTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPrivacyRoute: typeof AuthenticatedPrivacyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPrivacyRoute: AuthenticatedPrivacyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  NicoRoute: NicoRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MobileSettingsRoute: MobileSettingsRoute,
  MobileIndexRoute: MobileIndexRoute,
  ApiNicoSpeakRoute: ApiNicoSpeakRoute,
  ApiNicoThinkRoute: ApiNicoThinkRoute,
  ApiNicoTranscribeRoute: ApiNicoTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
